"""create initial data model tables

Revision ID: 4502d977e445
Revises: 
Create Date: 2026-07-19 12:35:52.874582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4502d977e445'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checking_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('starting_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_card_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('statement_close_day', sa.Integer(), nullable=False),
    sa.Column('payment_due_offset_days', sa.Integer(), nullable=False),
    sa.Column('starting_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurring_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('cash', 'credit', name='kind'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cadence_type', sa.Enum('weekly', 'biweekly', 'monthly', 'semi_monthly', 'quarterly', 'yearly', 'custom', name='cadencetype'), nullable=False),
    sa.Column('custom_interval_value', sa.Integer(), nullable=True),
    sa.Column('custom_interval_unit', sa.Enum('days', 'weeks', 'months', name='customintervalunit'), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('cash_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('credit_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recurring_series_id', sa.Integer(), nullable=True),
    sa.Column('occurrence_status', sa.Enum('attached', 'detached', 'skipped', name='occurrencestatus'), nullable=True),
    sa.ForeignKeyConstraint(['recurring_series_id'], ['recurring_series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('users')
    op.drop_table('recurring_series')
    op.drop_table('credit_card_settings')
    op.drop_table('checking_accounts')
    # ### end Alembic commands ###
